Let jq generate key from filename
Specifying a key on invocation is now optional,
and provided through the -k/-key option.

Json items are processed sequentially,
as popposed to being slurped up together,
which makes detecting individual filenames impossible.

diff --git a/json-wrap b/json-wrap
--- a/json-wrap
+++ b/json-wrap
@@ -3,40 +3,55 @@
 # SPDX-License-Identifier: MIT
 
 
-# json-wrap v0.1
+# json-wrap v0.2
 
 
-# wraps json in a top level object or array
+# wrap json in a top-level object
 
-# usage: json-wrap <name> [<file.json> ... ]
+# usage: json-wrap [-k <name>|--key <name>] [<file.json> ... ]
 #
-# Wraps provided json objects and outputs resulting json to stdout.
+# Reads Json from files, or stdin no files are specified,
+# and wraps each object, giving it a name specified by -k or --key.
 #
-# Reads object(s) from stdin if no files are specified.
+# If -k or --key is not specified, the key is generated
+# from the basename of the file, excluding any '.json' extension.
 #
-# If one object is provided it is wrapped in
-# a top level object named <name>.
+# The objects are printed sequentially to stdout.
 #
-# If more than one object is provided, they are wrapped in
-# an array named <name>.
+# Note that if objects are being read by stdin, then the
+# automatically- generated key will be "<stdin>", or possibly
+# a number representing a file descriptor
 #
-# If no objects are provided, the resultant json
-# will contain an empty array named <name>.
 #
 # Requires `jq` which does the heavy lifting.
 #
 
-help() { awk '/^ *[^#]/{exit}NR>1{print substr($0,2)}' $ZSH_ARGZERO; }
-version() { awk '$0~'"${(qqq)ZSH_ARGZERO:A:t}"'{print substr($0,2);exit}' $ZSH_ARGZERO; }
+help() { >&2 awk '/^ *[^#]/{exit}NR>1{print substr($0,2)}' $ZSH_ARGZERO; }
+version() { >&2 awk '$0~'"${(qqq)ZSH_ARGZERO:A:t}"'{print substr($0,2);exit}' $ZSH_ARGZERO; }
 
-case ${1:-} in
+opts=()
+while [[ ${1:-} = -* ]]
+do case ${1:-} in
 	-h|--help|) help; exit ;;
 	-v|--version) version; exit ;;
-	--)
-		shift ;&
-	*)
-		key=${1:-}
-		shift 2> /dev/null|| { help; exit } ;;
+	-k|--key)
+		shift
+		opts=(--arg key $1)
+		shift 2>/dev/null || {
+			echo 'Error: missing key. Use -h or --help for usage.'>&2
+			exit 1
+		} ;;
+	--) shift; break ;;
+	-*) break ;; # unrecognized options assumed to be positional arguments
 esac
+done
 
-jq --slurp "if length == 1 then .[0] else . end | { ${(qqq)key}: .  }" "$@"
+jq "${opts[@]}" '
+{
+	(
+		$ARGS.named.key? //
+		input_filename |
+		capture("(.*/)?(?<basename>.*?)(\\.json)?$").basename
+	): .
+}
+' "$@"
